context:
  version: "3.0.0"

package:
  name: git-hound
  version: ${{ version }}

source:
  url: https://github.com/tillson/git-hound/archive/v${{ version }}.tar.gz
  sha256: 09c612ec1af1bbbc5e1fc2da449083c3f3d71f1230c6f7c912039ca2ea81a101

build:
  number: 0

requirements:
  build:
    - ${{ compiler('go-cgo') }}
    - go-licenses
    - pkg-config
    - if: unix
      then:
        - ${{ compiler('c') }}
        - ${{ stdlib('c') }}
    - if: win
      then:
        - ${{ compiler('m2w64_c') }}
        - ${{ stdlib('m2w64_c') }}
        - m2-base
  host:
    - pcre

tests:
  - script:
      - git-hound --help

about:
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: Git plugin that prevents sensitive data from being committed.
  homepage: https://github.com/tillson/git-hound
  repository: https://github.com/tillson/git-hound

extra:
  recipe-maintainers:
    - danielnachun
